services:
  - type: web
    name: medicori-backend-bot
    env: node
    plan: free
    buildCommand: npm run install-all
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: DB_PATH
        value: ./medicalcore.db
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
